"""Add id to plates

Revision ID: 5265352e9721
Revises: e2dc88777553
Create Date: 2026-06-05 02:08:30.686647

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5265352e9721'
down_revision = 'e2dc88777553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plate', sa.Column('id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_plate_code'), 'plate', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plate_code'), table_name='plate')
    op.drop_column('plate', 'id')
    # ### end Alembic commands ###
