"""Add access events

Revision ID: a1b2c3d4e5f6
Revises: 5265352e9721
Create Date: 2026-06-05 20:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '5265352e9721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'access_events',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column('allowed', sa.Boolean(), nullable=False),
        sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_access_events_code'), 'access_events', ['code'], unique=False
    )
    op.create_index(
        op.f('ix_access_events_created_at'),
        'access_events',
        ['created_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_events_created_at'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_code'), table_name='access_events')
    op.drop_table('access_events')
    # ### end Alembic commands ###
